theme = "pickles"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render.space = "all"
render.tab = "all"
render.nbsp = "none"
render.nnbsp = "none"
render.newline = "none"
