theme = "pickles"

[editor]
line-number = "relative"
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render.space = "all"
render.tab = "all"
render.nbsp = "none"
render.nnbsp = "none"
render.newline = "none"

[keys.normal]
C-j = "page_down"
C-k = "page_up"
